// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: brands.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const addUserBrand = `-- name: AddUserBrand :exec
INSERT INTO user_brands (user_id, brand_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AddUserBrandParams struct {
	UserID  uuid.UUID `json:"user_id"`
	BrandID uuid.UUID `json:"brand_id"`
}

func (q *Queries) AddUserBrand(ctx context.Context, arg AddUserBrandParams) error {
	_, err := q.db.Exec(ctx, addUserBrand, arg.UserID, arg.BrandID)
	return err
}

const clearUserBrands = `-- name: ClearUserBrands :exec
DELETE FROM user_brands WHERE user_id = $1
`

func (q *Queries) ClearUserBrands(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearUserBrands, userID)
	return err
}

const createBrand = `-- name: CreateBrand :one
INSERT INTO brands (name, code, scope)
VALUES ($1, $2, COALESCE($3, 'national'))
RETURNING id, name, code, scope, created_at, updated_at
`

type CreateBrandParams struct {
	Name  string      `json:"name"`
	Code  string      `json:"code"`
	Scope interface{} `json:"scope"`
}

func (q *Queries) CreateBrand(ctx context.Context, arg CreateBrandParams) (Brand, error) {
	row := q.db.QueryRow(ctx, createBrand, arg.Name, arg.Code, arg.Scope)
	var i Brand
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Scope,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBrands = `-- name: ListBrands :many
SELECT id, name, code, scope, created_at, updated_at FROM brands ORDER BY name
`

func (q *Queries) ListBrands(ctx context.Context) ([]Brand, error) {
	rows, err := q.db.Query(ctx, listBrands)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Brand
	for rows.Next() {
		var i Brand
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Scope,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTerritories = `-- name: ListTerritories :many
SELECT id, brand_id, parent_id, name, level, pincode, created_at, updated_at FROM territories ORDER BY level, name
`

func (q *Queries) ListTerritories(ctx context.Context) ([]Territory, error) {
	rows, err := q.db.Query(ctx, listTerritories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Territory
	for rows.Next() {
		var i Territory
		if err := rows.Scan(
			&i.ID,
			&i.BrandID,
			&i.ParentID,
			&i.Name,
			&i.Level,
			&i.Pincode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserBrandIDs = `-- name: ListUserBrandIDs :many
SELECT brand_id FROM user_brands WHERE user_id = $1
`

func (q *Queries) ListUserBrandIDs(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listUserBrandIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var brand_id uuid.UUID
		if err := rows.Scan(&brand_id); err != nil {
			return nil, err
		}
		items = append(items, brand_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
