// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type Brand struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Code      string    `json:"code"`
	Scope     string    `json:"scope"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Permission struct {
	ID          uuid.UUID `json:"id"`
	Module      string    `json:"module"`
	Action      string    `json:"action"`
	Description *string   `json:"description"`
}

type Role struct {
	ID        uuid.UUID `json:"id"`
	Code      string    `json:"code"`
	Name      string    `json:"name"`
	Tier      string    `json:"tier"`
	IsSystem  bool      `json:"is_system"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type RolePermission struct {
	RoleID       uuid.UUID `json:"role_id"`
	PermissionID uuid.UUID `json:"permission_id"`
}

type Territory struct {
	ID        uuid.UUID  `json:"id"`
	BrandID   *uuid.UUID `json:"brand_id"`
	ParentID  *uuid.UUID `json:"parent_id"`
	Name      string     `json:"name"`
	Level     string     `json:"level"`
	Pincode   *string    `json:"pincode"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID  `json:"id"`
	RoleID       uuid.UUID  `json:"role_id"`
	ParentUserID *uuid.UUID `json:"parent_user_id"`
	Name         string     `json:"name"`
	Email        *string    `json:"email"`
	Phone        string     `json:"phone"`
	Username     *string    `json:"username"`
	PasswordHash *string    `json:"password_hash"`
	Status       string     `json:"status"`
	IsActive     bool       `json:"is_active"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
}

type UserBrand struct {
	UserID  uuid.UUID `json:"user_id"`
	BrandID uuid.UUID `json:"brand_id"`
}

type UserPermissionOverride struct {
	UserID       uuid.UUID `json:"user_id"`
	PermissionID uuid.UUID `json:"permission_id"`
	Granted      bool      `json:"granted"`
}

type UserTerritory struct {
	UserID      uuid.UUID `json:"user_id"`
	TerritoryID uuid.UUID `json:"territory_id"`
}
