// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: permissions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const clearUserOverrides = `-- name: ClearUserOverrides :exec
DELETE FROM user_permission_overrides WHERE user_id = $1
`

func (q *Queries) ClearUserOverrides(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearUserOverrides, userID)
	return err
}

const deleteUserOverride = `-- name: DeleteUserOverride :exec
DELETE FROM user_permission_overrides WHERE user_id = $1 AND permission_id = $2
`

type DeleteUserOverrideParams struct {
	UserID       uuid.UUID `json:"user_id"`
	PermissionID uuid.UUID `json:"permission_id"`
}

func (q *Queries) DeleteUserOverride(ctx context.Context, arg DeleteUserOverrideParams) error {
	_, err := q.db.Exec(ctx, deleteUserOverride, arg.UserID, arg.PermissionID)
	return err
}

const getPermissionByModuleAction = `-- name: GetPermissionByModuleAction :one
SELECT id, module, action, description FROM permissions WHERE module = $1 AND action = $2
`

type GetPermissionByModuleActionParams struct {
	Module string `json:"module"`
	Action string `json:"action"`
}

func (q *Queries) GetPermissionByModuleAction(ctx context.Context, arg GetPermissionByModuleActionParams) (Permission, error) {
	row := q.db.QueryRow(ctx, getPermissionByModuleAction, arg.Module, arg.Action)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Module,
		&i.Action,
		&i.Description,
	)
	return i, err
}

const getUserEffectivePermissions = `-- name: GetUserEffectivePermissions :many
SELECT p.module, p.action
FROM permissions p
WHERE p.id IN (
  SELECT rp.permission_id
  FROM users u
  JOIN role_permissions rp ON rp.role_id = u.role_id
  WHERE u.id = $1
    AND rp.permission_id NOT IN (
      SELECT permission_id FROM user_permission_overrides
      WHERE user_id = $1 AND granted = false
    )
  UNION
  SELECT permission_id FROM user_permission_overrides
  WHERE user_id = $1 AND granted = true
)
ORDER BY p.module, p.action
`

type GetUserEffectivePermissionsRow struct {
	Module string `json:"module"`
	Action string `json:"action"`
}

// Effective permissions = role-template grants (minus explicit revokes)
// UNION explicit per-user extra grants. This is the enforced RBAC set.
func (q *Queries) GetUserEffectivePermissions(ctx context.Context, id uuid.UUID) ([]GetUserEffectivePermissionsRow, error) {
	rows, err := q.db.Query(ctx, getUserEffectivePermissions, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserEffectivePermissionsRow
	for rows.Next() {
		var i GetUserEffectivePermissionsRow
		if err := rows.Scan(&i.Module, &i.Action); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissions = `-- name: ListPermissions :many
SELECT id, module, action, description FROM permissions ORDER BY module, action
`

func (q *Queries) ListPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Module,
			&i.Action,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolePermissions = `-- name: ListRolePermissions :many
SELECT p.module, p.action
FROM role_permissions rp
JOIN permissions p ON p.id = rp.permission_id
WHERE rp.role_id = $1
ORDER BY p.module, p.action
`

type ListRolePermissionsRow struct {
	Module string `json:"module"`
	Action string `json:"action"`
}

func (q *Queries) ListRolePermissions(ctx context.Context, roleID uuid.UUID) ([]ListRolePermissionsRow, error) {
	rows, err := q.db.Query(ctx, listRolePermissions, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRolePermissionsRow
	for rows.Next() {
		var i ListRolePermissionsRow
		if err := rows.Scan(&i.Module, &i.Action); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserOverrides = `-- name: ListUserOverrides :many
SELECT p.module, p.action, o.granted
FROM user_permission_overrides o
JOIN permissions p ON p.id = o.permission_id
WHERE o.user_id = $1
ORDER BY p.module, p.action
`

type ListUserOverridesRow struct {
	Module  string `json:"module"`
	Action  string `json:"action"`
	Granted bool   `json:"granted"`
}

func (q *Queries) ListUserOverrides(ctx context.Context, userID uuid.UUID) ([]ListUserOverridesRow, error) {
	rows, err := q.db.Query(ctx, listUserOverrides, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserOverridesRow
	for rows.Next() {
		var i ListUserOverridesRow
		if err := rows.Scan(&i.Module, &i.Action, &i.Granted); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUserOverride = `-- name: UpsertUserOverride :exec
INSERT INTO user_permission_overrides (user_id, permission_id, granted)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, permission_id) DO UPDATE SET granted = EXCLUDED.granted
`

type UpsertUserOverrideParams struct {
	UserID       uuid.UUID `json:"user_id"`
	PermissionID uuid.UUID `json:"permission_id"`
	Granted      bool      `json:"granted"`
}

func (q *Queries) UpsertUserOverride(ctx context.Context, arg UpsertUserOverrideParams) error {
	_, err := q.db.Exec(ctx, upsertUserOverride, arg.UserID, arg.PermissionID, arg.Granted)
	return err
}
