// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddUserBrand(ctx context.Context, arg AddUserBrandParams) error
	ClearUserBrands(ctx context.Context, userID uuid.UUID) error
	ClearUserOverrides(ctx context.Context, userID uuid.UUID) error
	CountUsers(ctx context.Context) (int64, error)
	CreateBrand(ctx context.Context, arg CreateBrandParams) (Brand, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteUser(ctx context.Context, id uuid.UUID) error
	DeleteUserOverride(ctx context.Context, arg DeleteUserOverrideParams) error
	GetPermissionByModuleAction(ctx context.Context, arg GetPermissionByModuleActionParams) (Permission, error)
	GetRoleByCode(ctx context.Context, code string) (Role, error)
	GetRoleByID(ctx context.Context, id uuid.UUID) (Role, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error)
	// Effective permissions = role-template grants (minus explicit revokes)
	// UNION explicit per-user extra grants. This is the enforced RBAC set.
	GetUserEffectivePermissions(ctx context.Context, id uuid.UUID) ([]GetUserEffectivePermissionsRow, error)
	// Login by email or username (case-insensitive).
	GetUserForLogin(ctx context.Context, lower string) (GetUserForLoginRow, error)
	ListBrands(ctx context.Context) ([]Brand, error)
	ListPermissions(ctx context.Context) ([]Permission, error)
	ListRolePermissions(ctx context.Context, roleID uuid.UUID) ([]ListRolePermissionsRow, error)
	ListRoles(ctx context.Context) ([]Role, error)
	ListTerritories(ctx context.Context) ([]Territory, error)
	ListUserBrandIDs(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error)
	ListUserOverrides(ctx context.Context, userID uuid.UUID) ([]ListUserOverridesRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	SetUserActive(ctx context.Context, arg SetUserActiveParams) error
	SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error
	SetUserStatus(ctx context.Context, arg SetUserStatusParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpsertUserOverride(ctx context.Context, arg UpsertUserOverrideParams) error
}

var _ Querier = (*Queries)(nil)
