// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  role_id, parent_user_id,
  name, email, phone, username, password_hash, status, is_active
) VALUES (
  $1, $4,
  $2, $5, $3, $6,
  $7,
  COALESCE($8, 'pending'),
  COALESCE($9, true)
)
RETURNING id, role_id, parent_user_id, name, email, phone, username, password_hash, status, is_active, created_at, updated_at
`

type CreateUserParams struct {
	RoleID       uuid.UUID   `json:"role_id"`
	Name         string      `json:"name"`
	Phone        string      `json:"phone"`
	ParentUserID *uuid.UUID  `json:"parent_user_id"`
	Email        *string     `json:"email"`
	Username     *string     `json:"username"`
	PasswordHash *string     `json:"password_hash"`
	Status       interface{} `json:"status"`
	IsActive     interface{} `json:"is_active"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.RoleID,
		arg.Name,
		arg.Phone,
		arg.ParentUserID,
		arg.Email,
		arg.Username,
		arg.PasswordHash,
		arg.Status,
		arg.IsActive,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.RoleID,
		&i.ParentUserID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Username,
		&i.PasswordHash,
		&i.Status,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT users.id, users.role_id, users.parent_user_id, users.name, users.email, users.phone, users.username, users.password_hash, users.status, users.is_active, users.created_at, users.updated_at, r.code AS role_code, r.name AS role_name, r.tier AS role_tier
FROM users
JOIN roles r ON r.id = users.role_id
WHERE users.id = $1
`

type GetUserByIDRow struct {
	User     User   `json:"user"`
	RoleCode string `json:"role_code"`
	RoleName string `json:"role_name"`
	RoleTier string `json:"role_tier"`
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.User.ID,
		&i.User.RoleID,
		&i.User.ParentUserID,
		&i.User.Name,
		&i.User.Email,
		&i.User.Phone,
		&i.User.Username,
		&i.User.PasswordHash,
		&i.User.Status,
		&i.User.IsActive,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
		&i.RoleCode,
		&i.RoleName,
		&i.RoleTier,
	)
	return i, err
}

const getUserForLogin = `-- name: GetUserForLogin :one
SELECT users.id, users.role_id, users.parent_user_id, users.name, users.email, users.phone, users.username, users.password_hash, users.status, users.is_active, users.created_at, users.updated_at, r.code AS role_code, r.tier AS role_tier
FROM users
JOIN roles r ON r.id = users.role_id
WHERE (lower(users.email) = lower($1) OR lower(users.username) = lower($1))
LIMIT 1
`

type GetUserForLoginRow struct {
	User     User   `json:"user"`
	RoleCode string `json:"role_code"`
	RoleTier string `json:"role_tier"`
}

// Login by email or username (case-insensitive).
func (q *Queries) GetUserForLogin(ctx context.Context, lower string) (GetUserForLoginRow, error) {
	row := q.db.QueryRow(ctx, getUserForLogin, lower)
	var i GetUserForLoginRow
	err := row.Scan(
		&i.User.ID,
		&i.User.RoleID,
		&i.User.ParentUserID,
		&i.User.Name,
		&i.User.Email,
		&i.User.Phone,
		&i.User.Username,
		&i.User.PasswordHash,
		&i.User.Status,
		&i.User.IsActive,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
		&i.RoleCode,
		&i.RoleTier,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT users.id, users.role_id, users.parent_user_id, users.name, users.email, users.phone, users.username, users.password_hash, users.status, users.is_active, users.created_at, users.updated_at,
       r.code AS role_code, r.name AS role_name, r.tier AS role_tier,
       COALESCE(array_agg(b.code ORDER BY b.code) FILTER (WHERE b.code IS NOT NULL), '{}')::text[] AS brand_codes
FROM users
JOIN roles r ON r.id = users.role_id
LEFT JOIN user_brands ub ON ub.user_id = users.id
LEFT JOIN brands b ON b.id = ub.brand_id
WHERE ($1::text IS NULL OR r.code = $1)
  AND ($2::text IS NULL OR users.status = $2)
  AND ($3::text IS NULL
       OR users.name ILIKE '%' || $3 || '%'
       OR users.email ILIKE '%' || $3 || '%'
       OR users.username ILIKE '%' || $3 || '%'
       OR users.phone ILIKE '%' || $3 || '%')
GROUP BY users.id, r.code, r.name, r.tier
ORDER BY users.created_at DESC
`

type ListUsersParams struct {
	RoleCode *string `json:"role_code"`
	Status   *string `json:"status"`
	Search   *string `json:"search"`
}

type ListUsersRow struct {
	User       User     `json:"user"`
	RoleCode   string   `json:"role_code"`
	RoleName   string   `json:"role_name"`
	RoleTier   string   `json:"role_tier"`
	BrandCodes []string `json:"brand_codes"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.RoleCode, arg.Status, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.User.ID,
			&i.User.RoleID,
			&i.User.ParentUserID,
			&i.User.Name,
			&i.User.Email,
			&i.User.Phone,
			&i.User.Username,
			&i.User.PasswordHash,
			&i.User.Status,
			&i.User.IsActive,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
			&i.RoleCode,
			&i.RoleName,
			&i.RoleTier,
			&i.BrandCodes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserActive = `-- name: SetUserActive :exec
UPDATE users SET is_active = $2 WHERE id = $1
`

type SetUserActiveParams struct {
	ID       uuid.UUID `json:"id"`
	IsActive bool      `json:"is_active"`
}

func (q *Queries) SetUserActive(ctx context.Context, arg SetUserActiveParams) error {
	_, err := q.db.Exec(ctx, setUserActive, arg.ID, arg.IsActive)
	return err
}

const setUserPassword = `-- name: SetUserPassword :exec
UPDATE users SET password_hash = $2 WHERE id = $1
`

type SetUserPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash *string   `json:"password_hash"`
}

func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error {
	_, err := q.db.Exec(ctx, setUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const setUserStatus = `-- name: SetUserStatus :exec
UPDATE users SET status = $2 WHERE id = $1
`

type SetUserStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) SetUserStatus(ctx context.Context, arg SetUserStatusParams) error {
	_, err := q.db.Exec(ctx, setUserStatus, arg.ID, arg.Status)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
  name           = COALESCE($2, name),
  email          = COALESCE($3, email),
  phone          = COALESCE($4, phone),
  username       = COALESCE($5, username),
  role_id        = COALESCE($6, role_id),
  parent_user_id = COALESCE($7, parent_user_id)
WHERE id = $1
RETURNING id, role_id, parent_user_id, name, email, phone, username, password_hash, status, is_active, created_at, updated_at
`

type UpdateUserParams struct {
	ID           uuid.UUID  `json:"id"`
	Name         *string    `json:"name"`
	Email        *string    `json:"email"`
	Phone        *string    `json:"phone"`
	Username     *string    `json:"username"`
	RoleID       *uuid.UUID `json:"role_id"`
	ParentUserID *uuid.UUID `json:"parent_user_id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Username,
		arg.RoleID,
		arg.ParentUserID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.RoleID,
		&i.ParentUserID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Username,
		&i.PasswordHash,
		&i.Status,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
